[cmd_duration]
min_time = 4
[git_branch]
symbol = " "
[git_status]
conflicted = "⇲"
[character]
use_symbol_for_status = true
[golang]
symbol = " "  #nerdfont icon
[ruby]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = " "
style = "bold blue"
[python]
symbol = " "
[rust]
symbol = " "
