[cmd_duration]
min_time = 4
[git_branch]
symbol = " "
[git_status]
conflicted = "[ﲅ ](fg:red bg:bright-black)"
ahead = "[ ×${count} ](fg:2 bg:5)"
behind = "[ ×${count} ](fg:5 bg:2)"
diverged = "[  ×${ahead_count}  ×${behind_count} ](bg:bright-black)"
untracked = "️[ ×${count} ](fg:215)"
stashed = " "
modified = "[ ×${count} ](bright-yellow)"
staged = "[ ×${count} ](bright-green)"
renamed = "[ ×${count} ](fg:214)"
deleted = "[ ×${count} ](bold bright-red )"
style = "bright-white"
format = "$all_status$ahead_behind"
[golang]
symbol = " "  #nerdfont icon
[ruby]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = " "
style = "bold blue"
[python]
symbol = " "
[rust]
symbol = " "
